name: admin
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  scoped_model: ^2.0.0-nullsafety.0
  rxdart: ^0.27.7
  http: ^0.13.4
  flutter_html_all: ^3.0.0-alpha.6
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.9
  country_code_picker: ^3.0.0
  url_launcher: ^6.1.3
  timeago: ^3.1.0
  flutter_rating_bar: ^4.0.0
  webview_flutter: ^4.2.1
  place_picker: ^0.10.0
  location: ^5.0.1
  sign_in_with_apple: ^5.0.0
  image_picker: ^0.8.5+3
  smooth_star_rating_null_safety: ^1.0.4+2
  #flutter_swiper_null_safety: ^1.0.2
  card_swiper: ^3.0.1
  lottie: ^2.5.0
  circular_menu: ^2.0.1
  #fab_circular_menu: ^1.0.2
  geocoding: ^2.0.1
  photo_view: ^0.14.0
  intro_slider: ^4.2.0
  pin_code_fields: ^8.0.1
  webview_cookie_manager: ^2.0.6
  intl: ^0.17.0
  #intl: ^0.18.0-nullsafety.2
  flutter_staggered_grid_view: ^0.4.1
  barcode_scan2: ^4.2.1
  rounded_loading_button: ^2.0.9
  tinycolor2: ^3.0.1
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  in_app_review: ^2.0.4
  #package_info: ^2.0.2
  package_info_plus: ^4.0.2
  firebase_messaging: ^14.1.1
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  firebase_analytics: ^10.0.6
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  #flutter_local_notifications: ^9.1.4
  firebase_dynamic_links: ^5.0.6
  google_sign_in: ^6.1.4
  share: ^2.0.4
  provider: ^6.0.1
  flex_color_scheme: ^7.0.4
  flutter_stripe: ^9.3.0
  #flutter_paystack: ^1.0.7
  #flutter_inappwebview: ^5.4.3+7
  razorpay_flutter: ^1.3.0
  #firebase_in_app_messaging: ^0.6.0+15
  flutter_firebase_chat_core: ^1.6.2
  flutter_chat_ui: ^1.6.3
  open_file_safe: ^3.2.3
  file_picker: ^5.3.3
  flutter_facebook_auth: ^5.0.11
  video_player: ^2.4.5
  chewie: ^1.3.4
  youtube_player_flutter: ^8.1.0
  loading_animation_widget: ^1.2.0+3
  flutter_native_splash: ^2.2.16
  animated_text_kit: ^4.2.2
  flutter_remix: ^0.0.3
  font_awesome_flutter: ^10.5.0
  wakelock_web: ^0.4.0
  just_audio: ^0.9.32
  flutter_slidable: ^2.0.0
  #google_fonts: ^2.3.1
  charts_flutter_new: ^0.12.0
  bluetooth_print: ^4.3.0
  pdf: ^3.8.1
  printing: ^5.9.1
  share_plus: ^4.0.4
  google_fonts: ^4.0.4
  #google_fonts: ^4.0.5



  #flutter_paystack: ^1.0.4+1
  #firebase_core_platform_interface: ^4.5.2
#  flutter_paystack:
#    git:
#      url: https://github.com/definitelyme/flutter_paystack.git
#      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01

dependency_overrides:
  image_picker_android: 0.8.4+13
  modal_bottom_sheet: ^3.0.0-pre
  intl: any
  ffi: ^2.0.2
  #intl: ^0.17.0-nullsafety.2
  #package_info_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.12.0
  package_info_plus: any

flutter_native_splash:
  image: assets/images/splash.png
  color: "#ffffff"
  ios_content_mode: scaleAspectFit
  android_gravity: center

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/sound/
    - assets/images/
    - assets/i18n/en.json
    - assets/i18n/ar.json
    - assets/i18n/es.json
    - assets/i18n/fr.json
    - assets/i18n/hi.json
    - assets/i18n/id.json
    - assets/i18n/chi.json
    - assets/i18n/pt.json
    - assets/i18n/ru.json
    - assets/images/upload_placeholder.png